
import com.itextpdf.kernel.font.PdfFontFactory;
import com.itextpdf.layout.element.Text;
import com.itextpdf.layout.property.TextAlignment;
import com.itextpdf.text.BaseColor;
import com.itextpdf.text.Document;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import com.itextpdf.text.Chunk;
import com.itextpdf.text.Element;
import com.itextpdf.text.Font;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.PageSize;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.Rectangle;
import com.itextpdf.text.pdf.PdfPCell;
import java.awt.Color;
import java.awt.Desktop;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;
import java.time.DayOfWeek;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.WindowConstants;
import javax.swing.table.DefaultTableModel;
import javax.swing.text.StyledEditorKit;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author SETTING
 */
public class Reporte extends javax.swing.JFrame {

    String cliente = "", domicilio = "", negocio = "", celular = "", asesor = "", cel_asesor = "", montotxt = "", cuotastxt = "", fecha_desembolso = "";
    float monto = 0, cuota = 0, num_cuotas = 0;
    String pdf = "";

    /**
     * Creates new form Reporte
     */
    public Reporte() {
        initComponents();
        setResizable(false);
        setTitle("INVERSIONES CREDIAMERICANA");
        setLocationRelativeTo(null);
        
        
        
        ImageIcon wallpaper =  new ImageIcon("src/images/wallpaper_crediamericana.png");
        Icon icono = new ImageIcon(wallpaper.getImage().getScaledInstance(jLabel_Wallpaper.getWidth(), jLabel_Wallpaper.getHeight(), Image.SCALE_DEFAULT));
        jLabel_Wallpaper.setIcon(icono);
    }
    
    @Override
    public Image getIconImage()
    {
        Image retValue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("images/logo_crediamericana_app.jpeg"));
        return retValue;
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        jLabel_footer = new javax.swing.JLabel();
        txt_nombreCliente = new javax.swing.JTextField();
        txt_Negocio = new javax.swing.JTextField();
        txt_cuotas = new javax.swing.JTextField();
        txt_Celular = new javax.swing.JTextField();
        txt_NombreUsuario = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txt_celularAsesor = new javax.swing.JTextField();
        txt_monto = new javax.swing.JTextField();
        jButton_REPORTE = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jButton_REPORTE1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txt_domicilio = new javax.swing.JTextPane();
        jLabel_footer1 = new javax.swing.JLabel();
        jLabel_Wallpaper = new javax.swing.JLabel();

        jTextField1.setText("jTextField1");

        jLabel_footer.setText("Creado por Anjhelo Elvis Vela Yauri");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_nombreCliente.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        txt_nombreCliente.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        getContentPane().add(txt_nombreCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 210, 25));

        txt_Negocio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_Negocio, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 230, 210, 25));

        txt_cuotas.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_cuotas, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, 100, 25));

        txt_Celular.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_Celular, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 210, 25));

        txt_NombreUsuario.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_NombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 50, 210, 25));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("N° CUOTAS:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(391, 160, 100, -1));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("CLIENTE:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 200, -1));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("DOMICILIO:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 200, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("NEGOCIO:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 200, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("CELULAR:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, 200, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("NOMBRE ASESOR:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 30, 200, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("CELULAR ASESOR:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 90, 200, -1));

        txt_celularAsesor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_celularAsesor, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, 210, 25));

        txt_monto.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        getContentPane().add(txt_monto, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, 100, 25));

        jButton_REPORTE.setBackground(new java.awt.Color(255, 51, 51));
        jButton_REPORTE.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_REPORTE.setForeground(new java.awt.Color(255, 255, 255));
        jButton_REPORTE.setText("GENERAR TARJETA");
        jButton_REPORTE.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton_REPORTE.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_REPORTE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_REPORTEActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_REPORTE, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 276, 210, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("CREDITO:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, 100, -1));

        jButton_REPORTE1.setBackground(new java.awt.Color(255, 51, 51));
        jButton_REPORTE1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton_REPORTE1.setForeground(new java.awt.Color(255, 255, 255));
        jButton_REPORTE1.setText("ABRIR PDF");
        jButton_REPORTE1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jButton_REPORTE1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton_REPORTE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_REPORTE1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton_REPORTE1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 230, 210, 40));

        txt_domicilio.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(txt_domicilio);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 210, 90));

        jLabel_footer1.setText("Creado por Anjhelo Elvis Vela Yauri");
        getContentPane().add(jLabel_footer1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 330, -1, -1));
        getContentPane().add(jLabel_Wallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_REPORTEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_REPORTEActionPerformed
        // TODO add your handling code here:
        
        cliente = txt_nombreCliente.getText();
        domicilio = txt_domicilio.getText();
        negocio = txt_Negocio.getText();
        celular = txt_Celular.getText();
        asesor = txt_NombreUsuario.getText();
        cel_asesor = txt_celularAsesor.getText();
        montotxt = txt_monto.getText().trim();
        cuotastxt = txt_cuotas.getText().trim();
        String texto_nota = "";

        
        LocalDate fecha_desembolso = LocalDate.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        
        
        if(!cliente.equals("") && !negocio.equals("") && !celular.equals("") && !asesor.equals("") && !cel_asesor.equals("") && !cuotastxt.equals("") && !montotxt.equals("") && isNumeric(cuotastxt) && isNumeric(montotxt) && isNumeric(cel_asesor) && isNumeric(celular))
        {
            Document documento = new Document();
            documento.setPageSize(new Rectangle(285, 566));

            if(cuotastxt.contains("."))
            {
                num_cuotas = Math.round(Float.parseFloat(cuotastxt.trim()));
            }
            else
            {
                num_cuotas = Float.parseFloat(cuotastxt.trim());
            }
            
            monto = Float.parseFloat(montotxt.trim());
            
            try {                
                String ruta = System.getProperty("user.home");
                PdfWriter.getInstance(documento, new FileOutputStream(ruta + "/Downloads/" + cliente + ".pdf"));
                pdf = ruta + "/Downloads/" + cliente + ".pdf";
                
                documento.setMargins(9, 9, 5, 5);
                
                
                com.itextpdf.text.Image header = com.itextpdf.text.Image.getInstance("src/images/logo_crediamericana.jpeg");
                header.scaleToFit(116, 1000);
                header.setAlignment(Chunk.ALIGN_CENTER);
                
                //Parrafo de Cliente
                Paragraph parrafo = new Paragraph();
                parrafo.setAlignment(Paragraph.ALIGN_LEFT);
                
                parrafo.setFont(FontFactory.getFont("Tahoma", 7, Font.BOLD, BaseColor.BLACK));
                parrafo.setIndentationRight(100);
                parrafo.setLeading(8);
                parrafo.add("\nCLIENTE: " + cliente.toUpperCase());
                parrafo.setSpacingAfter(4);
                
                //Parrafo de direccion
                Paragraph parrafo_direccion = new Paragraph();
                parrafo_direccion.setAlignment(Paragraph.ALIGN_LEFT);
                
                parrafo_direccion.setFont(FontFactory.getFont("Tahoma", 7, Font.BOLD, BaseColor.BLACK));
                parrafo_direccion.setIndentationRight(100);
                parrafo_direccion.setLeading(8);
                parrafo_direccion.add("DIRECCIÓN: " + domicilio.toUpperCase());
                parrafo_direccion.setSpacingAfter(4);
                
                Paragraph parrafo_negocio = new Paragraph();
                parrafo_negocio.setAlignment(Paragraph.ALIGN_LEFT);
                parrafo_negocio.setFont(FontFactory.getFont("Tahoma", 7, Font.BOLD, BaseColor.BLACK));
                parrafo_negocio.setIndentationRight(100);
                parrafo_negocio.setLeading(8);
                parrafo_negocio.add("NEGOCIO: " + negocio.toUpperCase());
                parrafo_negocio.setSpacingAfter(3);
                
                Paragraph parrafo_asesor = new Paragraph();
                parrafo_asesor.setAlignment(Paragraph.ALIGN_LEFT);
                parrafo_asesor.setFont(FontFactory.getFont("Tahoma", 7, Font.BOLD, BaseColor.BLACK));
                parrafo_asesor.setIndentationRight(100);
                parrafo_asesor.setLeading(8);
                parrafo_asesor.setSpacingBefore(4);
                parrafo_asesor.add("ASESOR: " + asesor.toUpperCase());
                parrafo_asesor.setSpacingAfter(4);
                
                Paragraph parrafo_desembolso = new Paragraph();
                parrafo_desembolso.setAlignment(Paragraph.ALIGN_LEFT);
                parrafo_desembolso.setFont(FontFactory.getFont("Tahoma", 7, Font.BOLD, BaseColor.BLACK));
                parrafo_desembolso.setIndentationRight(100);
                parrafo_desembolso.setFirstLineIndent(-10);
                parrafo_desembolso.setLeading(8);
                parrafo_desembolso.setAlignment(Paragraph.ALIGN_LEFT);
                parrafo_desembolso.add("DESEMBOLSO: " + fecha_desembolso.format(formatter));
                parrafo_desembolso.setSpacingAfter(6);
                
                Paragraph parrafo_celularC = new Paragraph();
                parrafo_celularC.setAlignment(Paragraph.ALIGN_LEFT);
                parrafo_celularC.setFont(FontFactory.getFont("Tahoma", 7, Font.BOLD, BaseColor.BLACK));
                parrafo_celularC.setIndentationRight(100);
                parrafo_celularC.setLeading(8);
                parrafo_celularC.add("CELULAR: " + celular);
                parrafo_celularC.setSpacingAfter(6);
                
                Paragraph parrafo_celularA = new Paragraph();
                parrafo_celularA.setAlignment(Paragraph.ALIGN_LEFT);
                parrafo_celularA.setFont(FontFactory.getFont("Tahoma", 7, Font.BOLD, BaseColor.BLACK));
                parrafo_celularA.setIndentationRight(100);
                parrafo_celularA.setLeading(8);
                parrafo_celularA.add("CELULAR: " + cel_asesor);
                parrafo_celularA.setSpacingAfter(6);
                
                //Tabla Desembolso - Celular:
                
                PdfPTable table_cel_desem = new PdfPTable(2);
                table_cel_desem.setHorizontalAlignment(Element.ALIGN_CENTER);
                table_cel_desem.setWidthPercentage(101.5f);
                
                PdfPCell celda_desem = new PdfPCell(parrafo_desembolso);
                celda_desem.setBorder(Rectangle.NO_BORDER);
                celda_desem.setHorizontalAlignment(PdfPCell.ALIGN_LEFT);
                
                table_cel_desem.addCell(celda_desem);
                
                PdfPCell celda_cel = new PdfPCell(parrafo_celularC);
                celda_cel.setBorder(Rectangle.NO_BORDER);
                
                table_cel_desem.addCell(celda_cel);
                
                //Tabla Asesor - Celular Asesor:
                
                PdfPTable table_Ase_Cel = new PdfPTable(2);
                table_Ase_Cel.setHorizontalAlignment(Element.ALIGN_CENTER);
                table_Ase_Cel.setWidthPercentage(101.5f);
                
                PdfPCell celda_Ase = new PdfPCell(parrafo_asesor);
                celda_Ase.setBorder(Rectangle.NO_BORDER);
                celda_Ase.setHorizontalAlignment(PdfPCell.ALIGN_LEFT);
                
                table_Ase_Cel.addCell(celda_Ase);
                
                PdfPCell celda_celA = new PdfPCell(parrafo_celularA);
                celda_celA.setBorder(Rectangle.NO_BORDER);
                
                table_Ase_Cel.addCell(celda_celA);
                //
                
                Paragraph parrafo_nota = new Paragraph();
                parrafo_nota.setLeading(8);
                parrafo_nota.setSpacingAfter(4.5f);
                Phrase fraseNota = new Phrase("NOTA: ", FontFactory.getFont("Tahoma", 5.5f, Font.BOLD, BaseColor.BLACK));
                parrafo_nota.add(fraseNota);
                Phrase fraseResto = new Phrase("Recuerde que por cada día de retraso en su crédito se aplicará un interés moratorio de 0.80.", FontFactory.getFont("Tahoma", 5.5f, Font.BOLD, BaseColor.BLACK));
                parrafo_nota.add(fraseResto);
                

                //Agregar parrafos:
                
                documento.open();
                documento.add(header);
                documento.add(parrafo);
                documento.add(parrafo_direccion);
                documento.add(parrafo_negocio);
                documento.add(table_cel_desem);
                
                
                PdfPTable tablaReporte = new PdfPTable(8);
                tablaReporte.setWidthPercentage(100);
                tablaReporte.setSpacingBefore(1);
                float[] medidaCeldas = {0.8f, 2.5f, 1.8f, 2.3f, 1.8f, 2, 2, 1.8f};
                tablaReporte.setWidths(medidaCeldas);
                tablaReporte.setHorizontalAlignment(Element.ALIGN_CENTER);
                
                Paragraph columna1 = new Paragraph("N°");
                columna1.getFont().setStyle(Font.BOLD);
                columna1.getFont().setSize(8.0f);
                PdfPCell celdaColumna1 = new PdfPCell(columna1);
                celdaColumna1.setHorizontalAlignment(PdfPCell.ALIGN_CENTER);
                tablaReporte.addCell(celdaColumna1);
                
                Paragraph columna2 = new Paragraph("F. Pago");
                columna2.getFont().setStyle((Font.BOLD));
                columna2.getFont().setSize(8.0f);
                PdfPCell celdaColumna2 = new PdfPCell(columna2);
                celdaColumna2.setHorizontalAlignment(PdfPCell.ALIGN_CENTER);
                tablaReporte.addCell(celdaColumna2);
                
                Paragraph columna3 = new Paragraph("Cuota");
                columna3.getFont().setStyle((Font.BOLD));
                columna3.getFont().setSize(8.0f);
                PdfPCell celdaColumna3 = new PdfPCell(columna3);
                celdaColumna3.setHorizontalAlignment(PdfPCell.ALIGN_CENTER);
                tablaReporte.addCell(celdaColumna3);
                
                Paragraph columna4 = new Paragraph("F. Cancel");
                columna4.getFont().setStyle((Font.BOLD));
                columna4.getFont().setSize(8.0f);
                PdfPCell celdaColumna4 = new PdfPCell(columna4);
                celdaColumna4.setHorizontalAlignment(PdfPCell.ALIGN_CENTER);
                tablaReporte.addCell(celdaColumna4);
                
                Paragraph columna5 = new Paragraph("Pago");
                columna5.getFont().setStyle((Font.BOLD));
                columna5.getFont().setSize(8.0f);
                PdfPCell celdaColumna5 = new PdfPCell(columna5);
                celdaColumna5.setHorizontalAlignment(PdfPCell.ALIGN_CENTER);
                tablaReporte.addCell(celdaColumna5);
                
                Paragraph columna6 = new Paragraph("Saldo");
                columna6.getFont().setStyle((Font.BOLD));
                columna6.getFont().setSize(8.0f);
                PdfPCell celdaColumna6 = new PdfPCell(columna6);
                celdaColumna6.setHorizontalAlignment(PdfPCell.ALIGN_CENTER);
                tablaReporte.addCell(celdaColumna6);
                
                Paragraph columna7 = new Paragraph("Saldo");
                columna7.getFont().setStyle((Font.BOLD));
                columna7.getFont().setSize(8.0f);
                PdfPCell celdaColumna7 = new PdfPCell(columna7);
                celdaColumna7.setHorizontalAlignment(PdfPCell.ALIGN_CENTER);
                tablaReporte.addCell(celdaColumna7);
                
                Paragraph columna8 = new Paragraph("Firma");
                columna8.getFont().setStyle((Font.BOLD));
                columna8.getFont().setSize(8.0f);
                PdfPCell celdaColumna8 = new PdfPCell(columna8);
                celdaColumna8.setHorizontalAlignment(PdfPCell.ALIGN_CENTER);
                tablaReporte.addCell(celdaColumna8);
            
                LocalDate fecha_pago = LocalDate.now().plusDays(1);
                
                cuota = (float) (Math.round((monto / num_cuotas) * 10.0) / 10.0);
                
                String resultado = String.format("%.2f", cuota);
                
                for (int i = 0; i <= num_cuotas; i++) 
                {
                    
                    if (fecha_pago.getDayOfWeek() == DayOfWeek.SUNDAY) 
                    {
                        fecha_pago = fecha_pago.plusDays(1);
                    }
                    
                    if(i == 0)
                    {
                        PdfPCell celdaNumero = new PdfPCell(new Phrase(""));
                        celdaNumero.setHorizontalAlignment(PdfPCell.ALIGN_CENTER);
                        
                        
                        PdfPCell celdaFechaPago = new PdfPCell(new Phrase(fecha_desembolso.format(formatter)));
                        celdaFechaPago.setHorizontalAlignment(PdfPCell.ALIGN_CENTER);
                        celdaFechaPago.setFixedHeight(15);
                        celdaFechaPago.setVerticalAlignment(PdfPCell.ALIGN_CENTER);
                        celdaFechaPago.setPhrase(new Phrase(fecha_desembolso.format(formatter), new Font(Font.FontFamily.HELVETICA, 8.0f)));
                        
                        
                        PdfPCell celdaCuota = new PdfPCell(new Phrase(""));
                        celdaCuota.setHorizontalAlignment(PdfPCell.ALIGN_CENTER);
                    
                        PdfPCell celdaCancel = new PdfPCell(new Phrase(""));
                        celdaCancel.setHorizontalAlignment(PdfPCell.ALIGN_CENTER);

                        PdfPCell celdaPago = new PdfPCell(new Phrase(""));
                        celdaPago.setHorizontalAlignment(PdfPCell.ALIGN_CENTER);
                        
                        String resultado_monto = String.format("%.2f", monto);
                        
                        PdfPCell celdaSaldo = new PdfPCell(new Phrase(resultado_monto));
                        celdaSaldo.setHorizontalAlignment(PdfPCell.ALIGN_CENTER);
                        celdaSaldo.setFixedHeight(15);
                        celdaSaldo.setVerticalAlignment(PdfPCell.ALIGN_CENTER);
                        celdaSaldo.setPhrase(new Phrase(resultado_monto, new Font(Font.FontFamily.HELVETICA, 8)));
                        
                        PdfPCell celdaSaldo2 = new PdfPCell(new Phrase(""));
                        celdaSaldo2.setHorizontalAlignment(PdfPCell.ALIGN_CENTER);
                    
                        PdfPCell celdaFirma = new PdfPCell(new Phrase(""));
                        celdaFirma.setHorizontalAlignment(PdfPCell.ALIGN_CENTER);
                        
                        tablaReporte.addCell(celdaNumero);
                        tablaReporte.addCell(celdaFechaPago);
                        tablaReporte.addCell(celdaCuota);
                        tablaReporte.addCell(celdaCancel);
                        tablaReporte.addCell(celdaPago);
                        tablaReporte.addCell(celdaSaldo);
                        tablaReporte.addCell(celdaSaldo2);
                        tablaReporte.addCell(celdaFirma);
                    }
                    
                    else
                    {
                        PdfPCell celdaNumero = new PdfPCell(new Phrase(Integer.toString(i)));
                        celdaNumero.setHorizontalAlignment(PdfPCell.ALIGN_CENTER);
                        celdaNumero.setFixedHeight(15);
                        celdaNumero.setVerticalAlignment(PdfPCell.ALIGN_CENTER);
                        celdaNumero.setPhrase(new Phrase(Integer.toString(i), new Font(Font.FontFamily.HELVETICA, 8)));

                        PdfPCell celdaFechaPago = new PdfPCell(new Phrase(fecha_pago.format(formatter)));
                        celdaFechaPago.setHorizontalAlignment(PdfPCell.ALIGN_CENTER);
                        celdaFechaPago.setFixedHeight(15);
                        celdaFechaPago.setVerticalAlignment(PdfPCell.ALIGN_CENTER);
                        celdaFechaPago.setPhrase(new Phrase(fecha_pago.format(formatter), new Font(Font.FontFamily.HELVETICA, 8.0f)));
                    
                        if(i == num_cuotas)
                        {
                            cuota = monto;
                            String resultado_final = String.format("%.2f", cuota);


                            PdfPCell celdaCuota = new PdfPCell(new Phrase(resultado_final));
                            celdaCuota.setPhrase(new Phrase(resultado_final, new Font(Font.FontFamily.HELVETICA, 8)));  // Adjust font size as needed
                            celdaCuota.setHorizontalAlignment(PdfPCell.ALIGN_CENTER);
                            celdaCuota.setFixedHeight(15);
                            celdaCuota.setVerticalAlignment(PdfPCell.ALIGN_CENTER);
                            celdaCuota.setPhrase(new Phrase(resultado_final, new Font(Font.FontFamily.HELVETICA, 8)));

                            PdfPCell celdaCancel = new PdfPCell(new Phrase(""));
                            celdaCancel.setHorizontalAlignment(PdfPCell.ALIGN_CENTER);
                            celdaCancel.setFixedHeight(15);
                            celdaCancel.setVerticalAlignment(PdfPCell.ALIGN_CENTER);

                            PdfPCell celdaPago = new PdfPCell(new Phrase(""));
                            celdaPago.setHorizontalAlignment(PdfPCell.ALIGN_CENTER);
                            celdaPago.setFixedHeight(15);
                            celdaPago.setVerticalAlignment(PdfPCell.ALIGN_CENTER);

                            monto = (float) (Math.round((monto - cuota) * 10.0) / 10.0);
                            String resultado_monto = String.format("%.2f", monto);

                            PdfPCell celdaSaldo = new PdfPCell(new Phrase(resultado_monto));
                            celdaSaldo.setHorizontalAlignment(PdfPCell.ALIGN_CENTER);
                            celdaSaldo.setFixedHeight(15);
                            celdaSaldo.setVerticalAlignment(PdfPCell.ALIGN_CENTER);
                            celdaSaldo.setPhrase(new Phrase(resultado_monto, new Font(Font.FontFamily.HELVETICA, 8)));

                            PdfPCell celdaSaldo2 = new PdfPCell(new Phrase(""));
                            celdaSaldo2.setHorizontalAlignment(PdfPCell.ALIGN_CENTER);
                            celdaSaldo2.setFixedHeight(15);
                            celdaSaldo2.setVerticalAlignment(PdfPCell.ALIGN_CENTER);

                            PdfPCell celdaFirma = new PdfPCell(new Phrase(""));
                            celdaFirma.setHorizontalAlignment(PdfPCell.ALIGN_CENTER);
                            celdaFirma.setFixedHeight(15);
                            celdaFirma.setVerticalAlignment(PdfPCell.ALIGN_CENTER);

                            tablaReporte.addCell(celdaNumero);
                            tablaReporte.addCell(celdaFechaPago);
                            tablaReporte.addCell(celdaCuota);
                            tablaReporte.addCell(celdaCancel);
                            tablaReporte.addCell(celdaPago);
                            tablaReporte.addCell(celdaSaldo);
                            tablaReporte.addCell(celdaSaldo2);
                            tablaReporte.addCell(celdaFirma);
                            fecha_pago = fecha_pago.plusDays(1);
                        }
                        else
                        {
                            PdfPCell celdaCuota = new PdfPCell(new Phrase(resultado));
                            celdaCuota.setHorizontalAlignment(PdfPCell.ALIGN_CENTER);
                            celdaCuota.setFixedHeight(15);
                            celdaCuota.setVerticalAlignment(PdfPCell.ALIGN_CENTER);
                            celdaCuota.setPhrase(new Phrase(resultado, new Font(Font.FontFamily.HELVETICA, 8)));

                            PdfPCell celdaCancel = new PdfPCell(new Phrase(""));
                            celdaCancel.setHorizontalAlignment(PdfPCell.ALIGN_CENTER);
                            celdaCancel.setFixedHeight(15);
                            celdaCancel.setVerticalAlignment(PdfPCell.ALIGN_CENTER);

                            PdfPCell celdaPago = new PdfPCell(new Phrase(""));
                            celdaPago.setHorizontalAlignment(PdfPCell.ALIGN_CENTER);
                            celdaPago.setFixedHeight(15);
                            celdaPago.setVerticalAlignment(PdfPCell.ALIGN_CENTER);

                            monto = (float) (Math.round((monto - cuota) * 10.0) / 10.0);
                            String resultado_monto = String.format("%.2f", monto);

                            PdfPCell celdaSaldo = new PdfPCell(new Phrase(resultado_monto));
                            celdaSaldo.setHorizontalAlignment(PdfPCell.ALIGN_CENTER);
                            celdaSaldo.setFixedHeight(15);
                            celdaSaldo.setVerticalAlignment(PdfPCell.ALIGN_CENTER);
                            celdaSaldo.setPhrase(new Phrase(resultado_monto, new Font(Font.FontFamily.HELVETICA, 8)));

                            PdfPCell celdaSaldo2 = new PdfPCell(new Phrase(""));
                            celdaSaldo2.setHorizontalAlignment(PdfPCell.ALIGN_CENTER);
                            celdaSaldo2.setFixedHeight(15);
                            celdaSaldo2.setVerticalAlignment(PdfPCell.ALIGN_CENTER);

                            PdfPCell celdaFirma = new PdfPCell(new Phrase(""));
                            celdaFirma.setHorizontalAlignment(PdfPCell.ALIGN_CENTER);
                            celdaFirma.setFixedHeight(15);
                            celdaFirma.setVerticalAlignment(PdfPCell.ALIGN_CENTER);

                            tablaReporte.addCell(celdaNumero);
                            tablaReporte.addCell(celdaFechaPago);
                            tablaReporte.addCell(celdaCuota);
                            tablaReporte.addCell(celdaCancel);
                            tablaReporte.addCell(celdaPago);
                            tablaReporte.addCell(celdaSaldo);
                            tablaReporte.addCell(celdaSaldo2);
                            tablaReporte.addCell(celdaFirma);
                            fecha_pago = fecha_pago.plusDays(1);
                        }
                    }
                    
                    
                    
                    
                    
                }
                documento.add(tablaReporte);
                documento.add(parrafo_nota);
                documento.add(table_Ase_Cel);
                
                documento.close();
                
            
                JOptionPane.showMessageDialog(null, "REPORTE CREADO");
                
                
               
            } catch (DocumentException  |IOException e) {
                
                System.out.println("Error en PDF o ruta de imagen" + e.getMessage());
                JOptionPane.showMessageDialog(null, "Error al cargar documento, contacte al programador.");
                
            }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Rellene todos los espacios correctamente.");
        }
        
        
    }//GEN-LAST:event_jButton_REPORTEActionPerformed

    private void jButton_REPORTE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_REPORTE1ActionPerformed
        // TODO add your handling code here:
        abrir(cliente);
    }
        
        public void abrir(String nombre_archivo)
        {
            try {
                File path = new File(pdf);
                Desktop.getDesktop().open(path);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Error al abrir pdf.");
                System.err.println("Error al abrir archivo." + e.getMessage());
                System.err.println(e);
            }
        
    }//GEN-LAST:event_jButton_REPORTE1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reporte.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reporte().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_REPORTE;
    private javax.swing.JButton jButton_REPORTE1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_Wallpaper;
    private javax.swing.JLabel jLabel_footer;
    private javax.swing.JLabel jLabel_footer1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField txt_Celular;
    private javax.swing.JTextField txt_Negocio;
    private javax.swing.JTextField txt_NombreUsuario;
    private javax.swing.JTextField txt_celularAsesor;
    private javax.swing.JTextField txt_cuotas;
    private javax.swing.JTextPane txt_domicilio;
    private javax.swing.JTextField txt_monto;
    private javax.swing.JTextField txt_nombreCliente;
    // End of variables declaration//GEN-END:variables

    public static boolean isNumeric(String cadena) {
    return cadena.matches("-?\\d+(\\.\\d+)?");
}

}
